/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GroupsIndexRouteImport } from './routes/groups.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as GroupsGroupIdRouteImport } from './routes/groups.$groupId'
import { Route as DashboardUsersRouteImport } from './routes/dashboard/users'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardMyGroupRouteImport } from './routes/dashboard/my-group'
import { Route as DashboardDocumentsRouteImport } from './routes/dashboard/documents'
import { Route as DashboardApplicationsRouteImport } from './routes/dashboard/applications'
import { Route as DashboardGroupsIndexRouteImport } from './routes/dashboard/groups.index'
import { Route as ApiDocumentsDownloadRouteImport } from './routes/api/documents/download'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIndexRoute = GroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const GroupsGroupIdRoute = GroupsGroupIdRouteImport.update({
  id: '/groups/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMyGroupRoute = DashboardMyGroupRouteImport.update({
  id: '/my-group',
  path: '/my-group',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDocumentsRoute = DashboardDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardApplicationsRoute = DashboardApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGroupsIndexRoute = DashboardGroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiDocumentsDownloadRoute = ApiDocumentsDownloadRouteImport.update({
  id: '/api/documents/download',
  path: '/api/documents/download',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/applications': typeof DashboardApplicationsRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/my-group': typeof DashboardMyGroupRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/groups/': typeof GroupsIndexRoute
  '/api/documents/download': typeof ApiDocumentsDownloadRoute
  '/dashboard/groups/': typeof DashboardGroupsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/login': typeof LoginRoute
  '/dashboard/applications': typeof DashboardApplicationsRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/my-group': typeof DashboardMyGroupRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/groups': typeof GroupsIndexRoute
  '/api/documents/download': typeof ApiDocumentsDownloadRoute
  '/dashboard/groups': typeof DashboardGroupsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apply': typeof ApplyRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/applications': typeof DashboardApplicationsRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/my-group': typeof DashboardMyGroupRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/groups/$groupId': typeof GroupsGroupIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/groups/': typeof GroupsIndexRoute
  '/api/documents/download': typeof ApiDocumentsDownloadRoute
  '/dashboard/groups/': typeof DashboardGroupsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apply'
    | '/dashboard'
    | '/login'
    | '/dashboard/applications'
    | '/dashboard/documents'
    | '/dashboard/my-group'
    | '/dashboard/profile'
    | '/dashboard/users'
    | '/groups/$groupId'
    | '/dashboard/'
    | '/groups/'
    | '/api/documents/download'
    | '/dashboard/groups/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apply'
    | '/login'
    | '/dashboard/applications'
    | '/dashboard/documents'
    | '/dashboard/my-group'
    | '/dashboard/profile'
    | '/dashboard/users'
    | '/groups/$groupId'
    | '/dashboard'
    | '/groups'
    | '/api/documents/download'
    | '/dashboard/groups'
  id:
    | '__root__'
    | '/'
    | '/apply'
    | '/dashboard'
    | '/login'
    | '/dashboard/applications'
    | '/dashboard/documents'
    | '/dashboard/my-group'
    | '/dashboard/profile'
    | '/dashboard/users'
    | '/groups/$groupId'
    | '/dashboard/'
    | '/groups/'
    | '/api/documents/download'
    | '/dashboard/groups/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplyRoute: typeof ApplyRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  GroupsGroupIdRoute: typeof GroupsGroupIdRoute
  GroupsIndexRoute: typeof GroupsIndexRoute
  ApiDocumentsDownloadRoute: typeof ApiDocumentsDownloadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/': {
      id: '/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof GroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/groups/$groupId': {
      id: '/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof GroupsGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/my-group': {
      id: '/dashboard/my-group'
      path: '/my-group'
      fullPath: '/dashboard/my-group'
      preLoaderRoute: typeof DashboardMyGroupRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/documents': {
      id: '/dashboard/documents'
      path: '/documents'
      fullPath: '/dashboard/documents'
      preLoaderRoute: typeof DashboardDocumentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/applications': {
      id: '/dashboard/applications'
      path: '/applications'
      fullPath: '/dashboard/applications'
      preLoaderRoute: typeof DashboardApplicationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/groups/': {
      id: '/dashboard/groups/'
      path: '/groups'
      fullPath: '/dashboard/groups/'
      preLoaderRoute: typeof DashboardGroupsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/documents/download': {
      id: '/api/documents/download'
      path: '/api/documents/download'
      fullPath: '/api/documents/download'
      preLoaderRoute: typeof ApiDocumentsDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardApplicationsRoute: typeof DashboardApplicationsRoute
  DashboardDocumentsRoute: typeof DashboardDocumentsRoute
  DashboardMyGroupRoute: typeof DashboardMyGroupRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardGroupsIndexRoute: typeof DashboardGroupsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardApplicationsRoute: DashboardApplicationsRoute,
  DashboardDocumentsRoute: DashboardDocumentsRoute,
  DashboardMyGroupRoute: DashboardMyGroupRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardGroupsIndexRoute: DashboardGroupsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplyRoute: ApplyRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  GroupsGroupIdRoute: GroupsGroupIdRoute,
  GroupsIndexRoute: GroupsIndexRoute,
  ApiDocumentsDownloadRoute: ApiDocumentsDownloadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
